language: node_js
node_js:
  - 'node'
  - 'lts/*'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-ox-ui-module' ]; then cd .. && eval "mv $currentfolder generator-ox-ui-module" && cd generator-ox-ui-module; fi

